# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-14 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('lead', models.CharField(max_length=255)),
                ('assignee_type', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='IssueLinkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=255)),
                ('inward', models.CharField(max_length=255)),
                ('outward', models.CharField(max_length=255)),
                ('link_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='IssueStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('icon_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IssueType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('type_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='JiraIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('assignee', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('environment', models.TextField()),
                ('resolution', models.CharField(max_length=255)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('due_time', models.DateTimeField()),
                ('resolution_date', models.DateTimeField()),
                ('votes', models.IntegerField(default=0)),
                ('watches', models.IntegerField(default=0)),
                ('time_original_estimate', models.IntegerField(default=0)),
                ('time_estimate', models.IntegerField(default=0)),
                ('time_spent', models.IntegerField(default=0)),
                ('issue_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synchronize_DB.IssueStatus')),
                ('issue_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synchronize_DB.IssueType')),
            ],
        ),
        migrations.CreateModel(
            name='JiraUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=60)),
                ('emailAddress', models.CharField(max_length=255)),
                ('displayName', models.CharField(max_length=255)),
                ('active', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('icon_url', models.CharField(max_length=255)),
                ('status_color', models.CharField(max_length=60)),
                ('priority_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('key', models.CharField(max_length=255)),
                ('project_id', models.IntegerField(default=0)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synchronize_DB.JiraUser')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('realised', models.CharField(max_length=10)),
                ('archived', models.CharField(max_length=10)),
                ('realise_date', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synchronize_DB.Project')),
            ],
        ),
        migrations.CreateModel(
            name='StatusCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=60)),
                ('color_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='jiraissue',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synchronize_DB.Priority'),
        ),
        migrations.AddField(
            model_name='jiraissue',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synchronize_DB.Project'),
        ),
        migrations.AddField(
            model_name='issuestatus',
            name='status_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synchronize_DB.StatusCategory'),
        ),
        migrations.AddField(
            model_name='component',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synchronize_DB.Project'),
        ),
    ]
