# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-14 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchronize_DB', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuestatus',
            name='sequence',
        ),
        migrations.RemoveField(
            model_name='jiraissue',
            name='resolution_date',
        ),
        migrations.AddField(
            model_name='issuestatus',
            name='stat_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statuscategory',
            name='stat_cat_id',
            field=models.IntegerField(default=0),
        ),
    ]
